### ISSUE TITLE
Out of memory CUDA

### ISSUE THREAD

**Issue by ntdat017** [HRNet/HRNet-Semantic-Segmentation#126]
```
Number of Layers
Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers
Traceback (most recent call last):
  File "tools/train.py", line 286, in <module>
    main()
  File "tools/train.py", line 251, in main
    device)
  File "HRNet-Semantic-Segmentation/tools/../lib/core/function.py", line 57, in train
    losses, _ = model(images, labels)
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "HRNet-Semantic-Segmentation/tools/../lib/utils/utils.py", line 34, in forward
    outputs = self.model(inputs)
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "HRNet-Semantic-Segmentation/tools/../lib/models/seg_hrnet.py", line 418, in forward
    x = self.layer1(x)
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "HRNet-Semantic-Segmentation/tools/../lib/models/seg_hrnet.py", line 94, in forward
    out = self.bn3(out)
  File "lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 466, in forward
    exponential_average_factor, self.eps)
  File "lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0; 10.76 GiB total capacity; 8.01 GiB already allocated; 760.56 MiB free; 8.23 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
```
I am trying to train in my own dataset but even reduce input size to 520x520 and batch_size is 1 on 1 gpus. I train model in 1 gpus.

**Comment by JACKYLUO1991** [comment]
@ntdat017 I have the same problem with you, have you solved it?

**Comment by renshasha** [comment]
运行python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml
时，出现cuda out of memory的错误。但是在运行python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml时，可以正常运行。所以是因为hrnet_ocr和hrnet的参数量多？还是由于其他原因？ 每一阶段的的通道数64，96,192，384是怎么设定的？有什么理论依据吗？

**Comment by EricHuiK** [comment]
> @ntdat017 I have the same problem with you, have you solved it?
torch.backends.cudnn.benchmark = True

**Comment by PkuRainBow** [comment]
Please try a smaller crop size.

**Comment by GutlapalliNikhil** [comment]
Hi @PkuRainBow , @JACKYLUO1991, @EricHuiK , @renshasha , @ntdat017 

When I start training the model I was not getting any CUDA memory errors. But when I stop the training and resume at some epoc, Its throwing CUDA out of memory error.
Because of that, If my data connections was interrupted, I again need to do train from start by deleting outputs folder and log folder.

Please help me in this.
Thank you.
