### ISSUE TITLE
invalid device ordinal

### ISSUE THREAD

**Issue by qifyin** [HRNet/HRNet-Semantic-Segmentation#171]
I use 3 GPUs to train it. But the error occurs. Do you have any solution?

RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:33
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "tools/train.py", line 289, in <module>
    main()
  File "tools/train.py", line 98, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/qfy/.conda/envs/HRnets-torch1.1/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)

**Comment by qifyin** [comment]
I have solved the problem. The  “--nproc_per_node” parameter is the number of GPUs. 
I set it wrong......My basic knowledge of CUDA programming is too poor......
The right code :  CUDA_VISIBLE_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node=3 --master_port=25901 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml
